# 1. Fundamental Data Types In Python `Pandas`

In [1]:
# Import the Python Pandas package, and set it as pd for the alias package name
import pandas as pd

# Import the Python NumPy package, and set it as np for the alias package name
import numpy as np

# Print the Python Pandas package version
print(pd.__version__)

# Print the Python NumPy package version
print(pd.__version__)

2.2.2
2.2.2

# DataFrame

A `DataFrame` is a 2-dimensional array that stores data of different types, such as integers, floating-point values, strings, lists, etc., in form of a table. To manually store data in a table, we'll need to use the `DataFrame` class. When we're using a Python dictionary of lists, the keys will be used as column headers, whereas the values will automatically correspond the column headers.

For instance, below is the example to manually store data in a table:

In [2]:
data = {
    "Name": ["Braund, Mr. Owen Harris", "Allen, Mr. William Henry", "Bonnel, Miss. Elizabeth"],
    "Age": [22, 35, 58],
    "Sex": ["Male", "Male", "Female"]
}

df = pd.DataFrame(data)
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    Male
1  Allen, Mr. William Henry   35    Male
2   Bonnel, Miss. Elizabeth   58  Female

# Series

A `Series` is a one-dimensional array that contains data of the same type. It also provides the ability to have labels for the indices, instead of normal integer indices.

In [3]:
# Create Python Pandas Series that has a sequence of floating-point values
nums = pd.Series([-1, -0.5, 0, 0.5, 1], dtype=np.float16) # The -1 and 1 integer values are automatically casted into floating-point values
nums

0   -1.0
1   -0.5
2    0.0
3    0.5
4    1.0
dtype: float16

In [4]:
# Indexing using integer value
print(f"The first index of nums has a value of = {nums[0]}")
print(f"The last index of nums has a value of = {nums[4]}")

The first index of nums has a value of = -1.0
The last index of nums has a value of = 1.0

Please do note that in Pandas, we can't use the -1 integer index to obtain the last value in a Series.

Below is the example when we used -1 to obtain the last value in a Series:

```ipython
# Indexing using integer value
[4]: print(f"The first index of nums has a value of = {nums[0]}")
     print(f"The last index of nums has a value of = {nums[-1]}")

The first index of nums has a value of = -1.0
```

<div style="background-color: rgba(255, 0, 0, 0.1); padding: 10px; border-left: 4px solid red; font-family: monospace; white-space: pre-wrap;">
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~\anaconda3\Lib\site-packages\pandas\core\indexes\range.py:413, in RangeIndex.get_loc(self, key)
    412 try:
--> 413     return self._range.index(new_key)
    414 except ValueError as err:

ValueError: -1 is not in range

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[12], line 3
      1 # Indexing using integer value
      2 print(f"The first index of nums has a value of = {nums[0]}")
----> 3 print(f"The last index of nums has a value of = {nums[-1]}")

File ~\anaconda3\Lib\site-packages\pandas\core\series.py:1121, in Series.__getitem__(self, key)
   1118     return self._values[key]
   1120 elif key_is_scalar:
-> 1121     return self._get_value(key)
   1123 # Convert generator to list before going through hashable part
   1124 # (We will iterate through the generator there to check for slices)
   1125 if is_iterator(key):

File ~\anaconda3\Lib\site-packages\pandas\core\series.py:1237, in Series._get_value(self, label, takeable)
   1234     return self._values[label]
   1236 # Similar to Index.get_value, but we do not fall back to positional
-> 1237 loc = self.index.get_loc(label)
   1239 if is_integer(loc):
   1240     return self._values[loc]

File ~\anaconda3\Lib\site-packages\pandas\core\indexes\range.py:415, in RangeIndex.get_loc(self, key)
    413         return self._range.index(new_key)
    414     except ValueError as err:
--> 415         raise KeyError(key) from err
    416 if isinstance(key, Hashable):
    417     raise KeyError(key)

KeyError: -1
</div>

In [5]:
# Use labels for the Series indices
grades = pd.Series([60, 85, 30, 100, 50], index=["Ali", "Gerry", "Mogi", "Pace", "Balu"])
grades

Ali       60
Gerry     85
Mogi      30
Pace     100
Balu      50
dtype: int64

In [6]:
# Indexing using labels
print(f"The first index of grades have a value of: {grades['Ali']}")

The first index of grades have a value of: 60

Selecting a single column of Python Pandas `DataFrame` yields a `Series`:

In [7]:
df["Name"]

0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2     Bonnel, Miss. Elizabeth
Name: Name, dtype: object

In [8]:
type(df["Name"])

pandas.core.series.Series

# Do Something To The `DataFrame` And `Series`

To perform a spesific task to the `DataFrame` and `Series`, we can use the methods that the objects provide.

In [9]:
# Get the maximum age
df["Age"].max()

58

In [10]:
# Get the maximum grade
grades.max()

100

In [11]:
# Show descriptive statistics of the DataFrame.
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000